#!/bin/sh


# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# shellcheck disable=2034


CONFIG_PROTECT="/usr/share/racket/gentoo/home/.racketrc"
